### ISSUE TITLE
Consider modeling documentation audiences and feedback processes

### ISSUE THREAD

**Issue by anarchivist** [hybox/models#57]
Chatting with @hannahfrost:

There are two primary audiences for this documentation:

* Developers, especially Hybox developers
* Folks wanting/needing to learn PCDM and data modling

Questions:

* Do we want to formally gather feedback from the community, so we can point to this as a community engagement process?
* How do we structure this so the feedback process is lightweight but meaningful?

**Comment by mjgiarlo** [comment]
@anarchivist :speech_balloon: 

> Do we want to formally gather feedback from the community, so we can point to this as a community engagement process?

As long as we have cycles for managing the community feedback process, I support this strongly. Which leads right into...

> How do we structure this so the feedback process is lightweight but meaningful?

Good question. Sending around a link to our documentation with succinctly expressed goals for feedback would help -- scoping the engagement effort for our communities. We could ask folks to limit their feedback to a small handful of areas where we're particularly uncertain or needing more buy-in (and, of course, welcome any and all feedback otherwise if given). We could set up a Google form, or the link, to gather input so it's all in one place and not littered across our inboxes, Slack channels, etc.?
